// Code generated by qtc from "components.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// package generator
//

//line generator/components.qtpl:3
package generator

//line generator/components.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generator/components.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generator/components.qtpl:3
func streamcomponentTemplate(qw422016 *qt422016.Writer, data *componentTmplData) {
//line generator/components.qtpl:3
	qw422016.N().S(`
package `)
//line generator/components.qtpl:4
	qw422016.E().S(data.PackageName)
//line generator/components.qtpl:4
	qw422016.N().S(`
`)
//line generator/components.qtpl:6
	if data.HasAnyEvents {
//line generator/components.qtpl:6
		qw422016.N().S(`
import "github.com/btvoidx/mint"
`)
//line generator/components.qtpl:8
	}
//line generator/components.qtpl:8
	qw422016.N().S(`

`)
//line generator/components.qtpl:11
	npp := data.Name.Plural.Pascal
	nsp := data.Name.Singular.Pascal
	nsc := data.Name.Singular.Camel
	ss := nsc + "Components"

//line generator/components.qtpl:15
	qw422016.N().S(`
type `)
//line generator/components.qtpl:17
	qw422016.E().S(nsp)
//line generator/components.qtpl:17
	qw422016.N().S(`Component struct {
`)
//line generator/components.qtpl:18
	for _, f := range data.Fields {
//line generator/components.qtpl:18
		qw422016.N().S(`    `)
//line generator/components.qtpl:19
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:19
		qw422016.N().S(` `)
//line generator/components.qtpl:19
		qw422016.E().S(f.Type.Singular.Original)
//line generator/components.qtpl:19
		qw422016.N().S(`
`)
//line generator/components.qtpl:20
	}
//line generator/components.qtpl:20
	qw422016.N().S(`}

func `)
//line generator/components.qtpl:23
	qw422016.E().S(nsp)
//line generator/components.qtpl:23
	qw422016.N().S(`ComponentFromValues(
`)
//line generator/components.qtpl:24
	for _, f := range data.Fields {
//line generator/components.qtpl:24
		qw422016.N().S(`    `)
//line generator/components.qtpl:25
		qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:25
		qw422016.N().S(`Arg `)
//line generator/components.qtpl:25
		qw422016.E().S(f.Type.Singular.Original)
//line generator/components.qtpl:25
		qw422016.N().S(`,
`)
//line generator/components.qtpl:26
	}
//line generator/components.qtpl:26
	qw422016.N().S(`) `)
//line generator/components.qtpl:27
	qw422016.E().S(nsp)
//line generator/components.qtpl:27
	qw422016.N().S(`Component {
    return `)
//line generator/components.qtpl:28
	qw422016.E().S(nsp)
//line generator/components.qtpl:28
	qw422016.N().S(`Component{
`)
//line generator/components.qtpl:29
	for _, f := range data.Fields {
//line generator/components.qtpl:29
		qw422016.N().S(`        `)
//line generator/components.qtpl:30
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:30
		qw422016.N().S(`: `)
//line generator/components.qtpl:30
		qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:30
		qw422016.N().S(`Arg,
`)
//line generator/components.qtpl:31
	}
//line generator/components.qtpl:31
	qw422016.N().S(`    }
}

func Default`)
//line generator/components.qtpl:35
	qw422016.E().S(nsp)
//line generator/components.qtpl:35
	qw422016.N().S(`Component() `)
//line generator/components.qtpl:35
	qw422016.E().S(nsp)
//line generator/components.qtpl:35
	qw422016.N().S(`Component {
    return `)
//line generator/components.qtpl:36
	qw422016.E().S(nsp)
//line generator/components.qtpl:36
	qw422016.N().S(`Component{
`)
//line generator/components.qtpl:37
	for _, f := range data.Fields {
//line generator/components.qtpl:37
		qw422016.N().S(`        `)
//line generator/components.qtpl:38
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:38
		qw422016.N().S(`: `)
//line generator/components.qtpl:38
		qw422016.N().S(f.ResetValue)
//line generator/components.qtpl:38
		qw422016.N().S(`,
`)
//line generator/components.qtpl:39
	}
//line generator/components.qtpl:39
	qw422016.N().S(`    }
}

func (c `)
//line generator/components.qtpl:43
	qw422016.E().S(nsp)
//line generator/components.qtpl:43
	qw422016.N().S(`Component) Clone() `)
//line generator/components.qtpl:43
	qw422016.E().S(nsp)
//line generator/components.qtpl:43
	qw422016.N().S(`Component {
    return `)
//line generator/components.qtpl:44
	qw422016.E().S(nsp)
//line generator/components.qtpl:44
	qw422016.N().S(`Component{
`)
//line generator/components.qtpl:45
	for _, f := range data.Fields {
//line generator/components.qtpl:45
		qw422016.N().S(`        `)
//line generator/components.qtpl:46
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:46
		qw422016.N().S(`: c.`)
//line generator/components.qtpl:46
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:46
		qw422016.N().S(`,
`)
//line generator/components.qtpl:47
	}
//line generator/components.qtpl:47
	qw422016.N().S(`    }
}


`)
//line generator/components.qtpl:52
	if data.IsOnlyOneField {
//line generator/components.qtpl:52
		qw422016.N().S(`    func (w *World) Set`)
//line generator/components.qtpl:53
		qw422016.E().S(nsp)
//line generator/components.qtpl:53
		qw422016.N().S(`(e Entity, arg `)
//line generator/components.qtpl:53
		qw422016.E().S(data.Fields[0].Type.Singular.Original)
//line generator/components.qtpl:53
		qw422016.N().S(`) (old `)
//line generator/components.qtpl:53
		qw422016.E().S(nsp)
//line generator/components.qtpl:53
		qw422016.N().S(`Component, wasAdded bool){
        c := `)
//line generator/components.qtpl:54
		qw422016.E().S(nsp)
//line generator/components.qtpl:54
		qw422016.N().S(`Component{
            `)
//line generator/components.qtpl:55
		qw422016.E().S(data.Fields[0].Name.Singular.Pascal)
//line generator/components.qtpl:55
		qw422016.N().S(`: arg,
        }
`)
//line generator/components.qtpl:57
	} else {
//line generator/components.qtpl:57
		qw422016.N().S(`    func (w *World) Set`)
//line generator/components.qtpl:58
		qw422016.E().S(nsp)
//line generator/components.qtpl:58
		qw422016.N().S(`(e Entity, c `)
//line generator/components.qtpl:58
		qw422016.E().S(nsp)
//line generator/components.qtpl:58
		qw422016.N().S(`Component) (old `)
//line generator/components.qtpl:58
		qw422016.E().S(nsp)
//line generator/components.qtpl:58
		qw422016.N().S(`Component, wasAdded bool) {
`)
//line generator/components.qtpl:59
	}
//line generator/components.qtpl:59
	qw422016.N().S(`    old, wasAdded = w.`)
//line generator/components.qtpl:60
	qw422016.E().S(ss)
//line generator/components.qtpl:60
	qw422016.N().S(`.Upsert(e, c);

    // depending on the generation flags, these might be unused
    _, _ = old, wasAdded

`)
//line generator/components.qtpl:65
	if data.ShouldGenAdded {
//line generator/components.qtpl:65
		qw422016.N().S(`    if wasAdded {
        fireEvent(w, `)
//line generator/components.qtpl:67
		qw422016.E().S(nsp)
//line generator/components.qtpl:67
		qw422016.N().S(`AddedEvent{Entity: e, Component: c})
    }
`)
//line generator/components.qtpl:69
	}
//line generator/components.qtpl:70
	if data.ShouldGenChanged {
//line generator/components.qtpl:70
		qw422016.N().S(`    fireEvent(w, `)
//line generator/components.qtpl:71
		qw422016.E().S(nsp)
//line generator/components.qtpl:71
		qw422016.N().S(`ChangedEvent{Entity: e, Old: old, New: c})
`)
//line generator/components.qtpl:72
	}
//line generator/components.qtpl:72
	qw422016.N().S(`
    return old, wasAdded
}

`)
//line generator/components.qtpl:77
	if !data.IsOnlyOneField {
//line generator/components.qtpl:77
		qw422016.N().S(`
func (w *World) Set`)
//line generator/components.qtpl:78
		qw422016.E().S(nsp)
//line generator/components.qtpl:78
		qw422016.N().S(`FromValues(
    e Entity,
`)
//line generator/components.qtpl:80
		for _, f := range data.Fields {
//line generator/components.qtpl:80
			qw422016.N().S(`    `)
//line generator/components.qtpl:81
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:81
			qw422016.N().S(`Arg `)
//line generator/components.qtpl:81
			qw422016.E().S(f.Type.Singular.Original)
//line generator/components.qtpl:81
			qw422016.N().S(`,
`)
//line generator/components.qtpl:82
		}
//line generator/components.qtpl:82
		qw422016.N().S(`) {
    old, _ := w.Set`)
//line generator/components.qtpl:84
		qw422016.E().S(nsp)
//line generator/components.qtpl:84
		qw422016.N().S(`(e, `)
//line generator/components.qtpl:84
		qw422016.E().S(nsp)
//line generator/components.qtpl:84
		qw422016.N().S(`Component{
`)
//line generator/components.qtpl:85
		for _, f := range data.Fields {
//line generator/components.qtpl:85
			qw422016.N().S(`        `)
//line generator/components.qtpl:86
			qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:86
			qw422016.N().S(`: `)
//line generator/components.qtpl:86
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:86
			qw422016.N().S(`Arg,
`)
//line generator/components.qtpl:87
		}
//line generator/components.qtpl:87
		qw422016.N().S(`    })

    // depending on the generation flags, these might be unused
    _ = old

`)
//line generator/components.qtpl:93
		if data.ShouldGenChanged {
//line generator/components.qtpl:93
			qw422016.N().S(`    fireEvent(w, `)
//line generator/components.qtpl:94
			qw422016.E().S(nsp)
//line generator/components.qtpl:94
			qw422016.N().S(`ChangedEvent{Entity: e, Old: old, New: w.Must`)
//line generator/components.qtpl:94
			qw422016.E().S(nsp)
//line generator/components.qtpl:94
			qw422016.N().S(`(e)})
`)
//line generator/components.qtpl:95
		}
//line generator/components.qtpl:95
		qw422016.N().S(`}
`)
//line generator/components.qtpl:97
	}
//line generator/components.qtpl:97
	qw422016.N().S(`

func (w *World) `)
//line generator/components.qtpl:99
	qw422016.E().S(nsp)
//line generator/components.qtpl:99
	qw422016.N().S(`(e Entity) (c `)
//line generator/components.qtpl:99
	qw422016.E().S(nsp)
//line generator/components.qtpl:99
	qw422016.N().S(`Component, ok bool) {
    return w.`)
//line generator/components.qtpl:100
	qw422016.E().S(ss)
//line generator/components.qtpl:100
	qw422016.N().S(`.Data(e)
}

func (w *World) Mutable`)
//line generator/components.qtpl:103
	qw422016.E().S(nsp)
//line generator/components.qtpl:103
	qw422016.N().S(`(e Entity) (c *`)
//line generator/components.qtpl:103
	qw422016.E().S(nsp)
//line generator/components.qtpl:103
	qw422016.N().S(`Component, ok bool) {
    return w.`)
//line generator/components.qtpl:104
	qw422016.E().S(ss)
//line generator/components.qtpl:104
	qw422016.N().S(`.DataMutable(e)
}

func (w *World) Must`)
//line generator/components.qtpl:107
	qw422016.E().S(nsp)
//line generator/components.qtpl:107
	qw422016.N().S(`(e Entity) `)
//line generator/components.qtpl:107
	qw422016.E().S(nsp)
//line generator/components.qtpl:107
	qw422016.N().S(`Component {
    c, ok := w.`)
//line generator/components.qtpl:108
	qw422016.E().S(ss)
//line generator/components.qtpl:108
	qw422016.N().S(`.Data(e)
    if !ok {
        panic("entity does not have `)
//line generator/components.qtpl:110
	qw422016.E().S(nsp)
//line generator/components.qtpl:110
	qw422016.N().S(`")
    }
    return c
}

func (w *World) Remove`)
//line generator/components.qtpl:115
	qw422016.E().S(nsp)
//line generator/components.qtpl:115
	qw422016.N().S(`(e Entity) {
    wasRemoved := w.`)
//line generator/components.qtpl:116
	qw422016.E().S(ss)
//line generator/components.qtpl:116
	qw422016.N().S(`.Remove(e)

    // depending on the generation flags, these might be unused
    _ = wasRemoved

`)
//line generator/components.qtpl:121
	if data.ShouldGenRemoved {
//line generator/components.qtpl:121
		qw422016.N().S(`    if wasRemoved {
        fireEvent(w, `)
//line generator/components.qtpl:123
		qw422016.E().S(nsp)
//line generator/components.qtpl:123
		qw422016.N().S(`RemovedEvent{Entity: e})
    }
`)
//line generator/components.qtpl:125
	}
//line generator/components.qtpl:125
	qw422016.N().S(`}

func (w *World) Has`)
//line generator/components.qtpl:128
	qw422016.E().S(nsp)
//line generator/components.qtpl:128
	qw422016.N().S(`(e Entity) bool {
    return w.`)
//line generator/components.qtpl:129
	qw422016.E().S(ss)
//line generator/components.qtpl:129
	qw422016.N().S(`.Contains(e)
}

func (w *World) `)
//line generator/components.qtpl:132
	qw422016.E().S(npp)
//line generator/components.qtpl:132
	qw422016.N().S(`Count() int {
    return w.`)
//line generator/components.qtpl:133
	qw422016.E().S(ss)
//line generator/components.qtpl:133
	qw422016.N().S(`.Len()
}

func (w *World) `)
//line generator/components.qtpl:136
	qw422016.E().S(npp)
//line generator/components.qtpl:136
	qw422016.N().S(`Capacity() int {
    return w.`)
//line generator/components.qtpl:137
	qw422016.E().S(ss)
//line generator/components.qtpl:137
	qw422016.N().S(`.Cap()
}

func (w *World) All`)
//line generator/components.qtpl:140
	qw422016.E().S(npp)
//line generator/components.qtpl:140
	qw422016.N().S(`(yield func(e Entity, c `)
//line generator/components.qtpl:140
	qw422016.E().S(nsp)
//line generator/components.qtpl:140
	qw422016.N().S(`Component) bool) {
    for e, c := range w.`)
//line generator/components.qtpl:141
	qw422016.E().S(ss)
//line generator/components.qtpl:141
	qw422016.N().S(`.All {
        if !yield(e, c) {
            break
        }
    }
}

func (w *World) AllMutable`)
//line generator/components.qtpl:148
	qw422016.E().S(npp)
//line generator/components.qtpl:148
	qw422016.N().S(`(yield func(e Entity, c *`)
//line generator/components.qtpl:148
	qw422016.E().S(nsp)
//line generator/components.qtpl:148
	qw422016.N().S(`Component) bool) {
    for e, c := range w.`)
//line generator/components.qtpl:149
	qw422016.E().S(ss)
//line generator/components.qtpl:149
	qw422016.N().S(`.AllMutable {
        if !yield(e, c) {
            break
        }
    }
}

func (w *World) All`)
//line generator/components.qtpl:156
	qw422016.E().S(npp)
//line generator/components.qtpl:156
	qw422016.N().S(`Entities(yield func(e Entity) bool) {
    for e := range w.`)
//line generator/components.qtpl:157
	qw422016.E().S(ss)
//line generator/components.qtpl:157
	qw422016.N().S(`.AllEntities {
        if !yield(e) {
            break
        }
    }
}

// `)
//line generator/components.qtpl:164
	qw422016.E().S(nsp)
//line generator/components.qtpl:164
	qw422016.N().S(`Builder
`)
//line generator/components.qtpl:165
	if data.IsOnlyOneField {
//line generator/components.qtpl:165
		qw422016.N().S(`
func With`)
//line generator/components.qtpl:166
		qw422016.E().S(nsp)
//line generator/components.qtpl:166
		qw422016.N().S(`(arg `)
//line generator/components.qtpl:166
		qw422016.E().S(data.Fields[0].Type.Singular.Original)
//line generator/components.qtpl:166
		qw422016.N().S(`) EntityBuilderOption {
    c := `)
//line generator/components.qtpl:167
		qw422016.E().S(nsp)
//line generator/components.qtpl:167
		qw422016.N().S(`Component{
        `)
//line generator/components.qtpl:168
		qw422016.E().S(data.Fields[0].Name.Singular.Pascal)
//line generator/components.qtpl:168
		qw422016.N().S(`: arg,
    }
`)
//line generator/components.qtpl:170
	} else {
//line generator/components.qtpl:170
		qw422016.N().S(`
func With`)
//line generator/components.qtpl:171
		qw422016.E().S(nsp)
//line generator/components.qtpl:171
		qw422016.N().S(`(c `)
//line generator/components.qtpl:171
		qw422016.E().S(nsp)
//line generator/components.qtpl:171
		qw422016.N().S(`Component) EntityBuilderOption {
`)
//line generator/components.qtpl:172
	}
//line generator/components.qtpl:172
	qw422016.N().S(`
    return func(w *World, e Entity) {
        w.`)
//line generator/components.qtpl:174
	qw422016.E().S(ss)
//line generator/components.qtpl:174
	qw422016.N().S(`.Upsert(e, c)
    }
}

`)
//line generator/components.qtpl:178
	if !data.IsOnlyOneField {
//line generator/components.qtpl:178
		qw422016.N().S(`
func With`)
//line generator/components.qtpl:179
		qw422016.E().S(nsp)
//line generator/components.qtpl:179
		qw422016.N().S(`FromValues(
`)
//line generator/components.qtpl:180
		for _, f := range data.Fields {
//line generator/components.qtpl:180
			qw422016.N().S(`    `)
//line generator/components.qtpl:181
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:181
			qw422016.N().S(`Arg `)
//line generator/components.qtpl:181
			qw422016.E().S(f.Type.Singular.Original)
//line generator/components.qtpl:181
			qw422016.N().S(`,
`)
//line generator/components.qtpl:182
		}
//line generator/components.qtpl:182
		qw422016.N().S(`) EntityBuilderOption {
    return func(w *World, e Entity) {
        w.Set`)
//line generator/components.qtpl:185
		qw422016.E().S(nsp)
//line generator/components.qtpl:185
		qw422016.N().S(`FromValues(e,
`)
//line generator/components.qtpl:186
		for _, f := range data.Fields {
//line generator/components.qtpl:186
			qw422016.N().S(`            `)
//line generator/components.qtpl:187
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:187
			qw422016.N().S(`Arg,
`)
//line generator/components.qtpl:188
		}
//line generator/components.qtpl:188
		qw422016.N().S(`        )
    }
}
`)
//line generator/components.qtpl:192
	}
//line generator/components.qtpl:192
	qw422016.N().S(`


// Events
`)
//line generator/components.qtpl:196
	if data.ShouldGenAdded {
//line generator/components.qtpl:196
		qw422016.N().S(`type `)
//line generator/components.qtpl:197
		qw422016.E().S(nsp)
//line generator/components.qtpl:197
		qw422016.N().S(`AddedEvent struct {
    Entity Entity
    Component `)
//line generator/components.qtpl:199
		qw422016.E().S(nsp)
//line generator/components.qtpl:199
		qw422016.N().S(`Component
}
func (w *World) On`)
//line generator/components.qtpl:201
		qw422016.E().S(nsp)
//line generator/components.qtpl:201
		qw422016.N().S(`Added(fn func(evt `)
//line generator/components.qtpl:201
		qw422016.E().S(nsp)
//line generator/components.qtpl:201
		qw422016.N().S(`AddedEvent)) UnsubscribeFunc {
    unsub := mint.On(w.eventBus, fn)
    return func() {
        unsub()
    }
}
`)
//line generator/components.qtpl:207
	}
//line generator/components.qtpl:207
	qw422016.N().S(`
`)
//line generator/components.qtpl:209
	if data.ShouldGenRemoved {
//line generator/components.qtpl:209
		qw422016.N().S(`type `)
//line generator/components.qtpl:210
		qw422016.E().S(nsp)
//line generator/components.qtpl:210
		qw422016.N().S(`RemovedEvent struct {
    Entity Entity
    Component `)
//line generator/components.qtpl:212
		qw422016.E().S(nsp)
//line generator/components.qtpl:212
		qw422016.N().S(`Component
}
func (w *World) On`)
//line generator/components.qtpl:214
		qw422016.E().S(nsp)
//line generator/components.qtpl:214
		qw422016.N().S(`Removed(fn func(evt `)
//line generator/components.qtpl:214
		qw422016.E().S(nsp)
//line generator/components.qtpl:214
		qw422016.N().S(`RemovedEvent)) UnsubscribeFunc {
    unsub := mint.On(w.eventBus, fn)
    return func() {
        unsub()
    }
}
`)
//line generator/components.qtpl:220
	}
//line generator/components.qtpl:220
	qw422016.N().S(`
`)
//line generator/components.qtpl:222
	if data.ShouldGenChanged {
//line generator/components.qtpl:222
		qw422016.N().S(`type `)
//line generator/components.qtpl:223
		qw422016.E().S(nsp)
//line generator/components.qtpl:223
		qw422016.N().S(`ChangedEvent struct {
    Entity Entity
    Old, New `)
//line generator/components.qtpl:225
		qw422016.E().S(nsp)
//line generator/components.qtpl:225
		qw422016.N().S(`Component
}
func (w *World) On`)
//line generator/components.qtpl:227
		qw422016.E().S(nsp)
//line generator/components.qtpl:227
		qw422016.N().S(`Changed(fn func(evt `)
//line generator/components.qtpl:227
		qw422016.E().S(nsp)
//line generator/components.qtpl:227
		qw422016.N().S(`ChangedEvent)) UnsubscribeFunc {
	unsub := mint.On(w.eventBus, fn)
	return func() {
		unsub()
	}
}
`)
//line generator/components.qtpl:233
	}
//line generator/components.qtpl:233
	qw422016.N().S(`
// Resource methods
`)
//line generator/components.qtpl:236
	if data.IsOnlyOneField {
//line generator/components.qtpl:236
		qw422016.N().S(`
func (w *World) Set`)
//line generator/components.qtpl:237
		qw422016.E().S(nsp)
//line generator/components.qtpl:237
		qw422016.N().S(`Resource(arg `)
//line generator/components.qtpl:237
		qw422016.E().S(data.Fields[0].Type.Singular.Original)
//line generator/components.qtpl:237
		qw422016.N().S(`) {
    w.Set`)
//line generator/components.qtpl:238
		qw422016.E().S(nsp)
//line generator/components.qtpl:238
		qw422016.N().S(`(w.resourceEntity, arg)
}
`)
//line generator/components.qtpl:240
	} else {
//line generator/components.qtpl:240
		qw422016.N().S(`
func (w *World) Set`)
//line generator/components.qtpl:241
		qw422016.E().S(nsp)
//line generator/components.qtpl:241
		qw422016.N().S(`Resource(c `)
//line generator/components.qtpl:241
		qw422016.E().S(nsp)
//line generator/components.qtpl:241
		qw422016.N().S(`Component) {
    w.Set`)
//line generator/components.qtpl:242
		qw422016.E().S(nsp)
//line generator/components.qtpl:242
		qw422016.N().S(`(w.resourceEntity, c)
}
`)
//line generator/components.qtpl:244
	}
//line generator/components.qtpl:244
	qw422016.N().S(`

`)
//line generator/components.qtpl:246
	if !data.IsOnlyOneField {
//line generator/components.qtpl:246
		qw422016.N().S(`
func (w *World) Set`)
//line generator/components.qtpl:247
		qw422016.E().S(nsp)
//line generator/components.qtpl:247
		qw422016.N().S(`ResourceFromValues(
`)
//line generator/components.qtpl:248
		for _, f := range data.Fields {
//line generator/components.qtpl:248
			qw422016.N().S(`    `)
//line generator/components.qtpl:249
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:249
			qw422016.N().S(`Arg `)
//line generator/components.qtpl:249
			qw422016.E().S(f.Type.Singular.Original)
//line generator/components.qtpl:249
			qw422016.N().S(`,
`)
//line generator/components.qtpl:250
		}
//line generator/components.qtpl:250
		qw422016.N().S(`) {
   w.Set`)
//line generator/components.qtpl:252
		qw422016.E().S(nsp)
//line generator/components.qtpl:252
		qw422016.N().S(`Resource(`)
//line generator/components.qtpl:252
		qw422016.E().S(nsp)
//line generator/components.qtpl:252
		qw422016.N().S(`Component{
`)
//line generator/components.qtpl:253
		for _, f := range data.Fields {
//line generator/components.qtpl:253
			qw422016.N().S(`        `)
//line generator/components.qtpl:254
			qw422016.E().S(f.Name.Singular.Pascal)
//line generator/components.qtpl:254
			qw422016.N().S(`: `)
//line generator/components.qtpl:254
			qw422016.E().S(f.Name.Singular.Camel)
//line generator/components.qtpl:254
			qw422016.N().S(`Arg,
`)
//line generator/components.qtpl:255
		}
//line generator/components.qtpl:255
		qw422016.N().S(`    })
}
`)
//line generator/components.qtpl:258
	}
//line generator/components.qtpl:258
	qw422016.N().S(`

func (w *World) `)
//line generator/components.qtpl:260
	qw422016.E().S(nsp)
//line generator/components.qtpl:260
	qw422016.N().S(`Resource() (`)
//line generator/components.qtpl:260
	qw422016.E().S(nsp)
//line generator/components.qtpl:260
	qw422016.N().S(`Component,bool) {
    return w.`)
//line generator/components.qtpl:261
	qw422016.E().S(ss)
//line generator/components.qtpl:261
	qw422016.N().S(`.Data(w.resourceEntity)
}

func (w *World) Must`)
//line generator/components.qtpl:264
	qw422016.E().S(nsp)
//line generator/components.qtpl:264
	qw422016.N().S(`Resource() `)
//line generator/components.qtpl:264
	qw422016.E().S(nsp)
//line generator/components.qtpl:264
	qw422016.N().S(`Component {
    c, ok := w.`)
//line generator/components.qtpl:265
	qw422016.E().S(nsp)
//line generator/components.qtpl:265
	qw422016.N().S(`Resource()
    if !ok {
        panic("resource entity does not have `)
//line generator/components.qtpl:267
	qw422016.E().S(nsp)
//line generator/components.qtpl:267
	qw422016.N().S(`")
    }
    return c
}

func (w *World) Remove`)
//line generator/components.qtpl:272
	qw422016.E().S(nsp)
//line generator/components.qtpl:272
	qw422016.N().S(`Resource() {
    w.`)
//line generator/components.qtpl:273
	qw422016.E().S(ss)
//line generator/components.qtpl:273
	qw422016.N().S(`.Remove(w.resourceEntity)
}

func (w *World) Has`)
//line generator/components.qtpl:276
	qw422016.E().S(nsp)
//line generator/components.qtpl:276
	qw422016.N().S(`Resource() bool {
    return w.`)
//line generator/components.qtpl:277
	qw422016.E().S(ss)
//line generator/components.qtpl:277
	qw422016.N().S(`.Contains(w.resourceEntity)
}


`)
//line generator/components.qtpl:281
}

//line generator/components.qtpl:281
func writecomponentTemplate(qq422016 qtio422016.Writer, data *componentTmplData) {
//line generator/components.qtpl:281
	qw422016 := qt422016.AcquireWriter(qq422016)
//line generator/components.qtpl:281
	streamcomponentTemplate(qw422016, data)
//line generator/components.qtpl:281
	qt422016.ReleaseWriter(qw422016)
//line generator/components.qtpl:281
}

//line generator/components.qtpl:281
func componentTemplate(data *componentTmplData) string {
//line generator/components.qtpl:281
	qb422016 := qt422016.AcquireByteBuffer()
//line generator/components.qtpl:281
	writecomponentTemplate(qb422016, data)
//line generator/components.qtpl:281
	qs422016 := string(qb422016.B)
//line generator/components.qtpl:281
	qt422016.ReleaseByteBuffer(qb422016)
//line generator/components.qtpl:281
	return qs422016
//line generator/components.qtpl:281
}
