// Code generated by qtc from "entities_go.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// package generator
//

//line generator/entities_go.qtpl:3
package generator

//line generator/entities_go.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generator/entities_go.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generator/entities_go.qtpl:3
func streamentitiesTemplate(qw422016 *qt422016.Writer, data *ecsTmplData) {
//line generator/entities_go.qtpl:3
	qw422016.N().S(`
package `)
//line generator/entities_go.qtpl:4
	qw422016.E().S(data.PackageName)
//line generator/entities_go.qtpl:4
	qw422016.N().S(`

const (
	indexBits      = 12
	generationBits = 20
	indexMask      = (1 << indexBits) - 1
	generationMask = (1 << generationBits) - 1
	maxEntities    = 1 << indexBits
)

var Tombstone = Entity(maxEntities)

type Entity uint32

func NewEntity(index, generation int) Entity {
	return Entity((generation << generationBits) | index)
}

func (e Entity) Index() int {
	return int(e) & indexMask
}

func (e Entity) Generation() int {
	return int(e) >> indexBits
}

func (e Entity) In(entities ...Entity) bool {
	for _, entity := range entities {
		if e == entity {
			return true
		}
	}
	return false
}

func SortEntities(fn func(yield func(entity Entity) bool)) []Entity {
	entities := make([]Entity, 0, 4096)
	for e := range fn {
		entities = append(entities, e)
	}

	slices.Sort(entities)

	return entities
}

type EntityBuilderOption func(w *World, entity Entity)

func(w *World) CreateEntities(count int, opts ...EntityBuilderOption) []Entity{
    entities := make([]Entity, count)
    for i := range entities {
        var entity Entity

        if w.freeEntities.Len() == 0 {
            entity = Entity(w.nextEntityID)
            w.nextEntityID++
        } else {
            entity = w.freeEntities.dense[0]
            w.freeEntities.Remove(entity)
        }
        w.livingEntities.Upsert(entity, empty{})
        entities[i] = entity

		for _, opt := range opts {
			opt(w, entity)
		}
    }
    return entities
}

func (w *World) CreateEntity(opts ...EntityBuilderOption) Entity {
	return w.CreateEntities(1, opts...)[0]
}

func (w *World) DestroyEntities(entities ...Entity) {
	for _, entity := range entities {
		w.livingEntities.Remove(entity)
		w.freeEntities.Upsert(entity,empty{})

`)
//line generator/entities_go.qtpl:83
	for _, c := range data.Components {
//line generator/entities_go.qtpl:84
		if c.IsTag {
//line generator/entities_go.qtpl:84
			qw422016.N().S(`		w.`)
//line generator/entities_go.qtpl:85
			qw422016.E().S(c.Name.Singular.Camel)
//line generator/entities_go.qtpl:85
			qw422016.N().S(`Tags.Remove(entity)
`)
//line generator/entities_go.qtpl:86
		} else {
//line generator/entities_go.qtpl:86
			qw422016.N().S(`		w.`)
//line generator/entities_go.qtpl:87
			qw422016.E().S(c.Name.Singular.Camel)
//line generator/entities_go.qtpl:87
			qw422016.N().S(`Components.Remove(entity)
`)
//line generator/entities_go.qtpl:88
		}
//line generator/entities_go.qtpl:89
	}
//line generator/entities_go.qtpl:89
	qw422016.N().S(`	}
}

func (w *World) IsAlive(entity Entity) bool {
	return w.livingEntities.Contains(entity)
}

func (w *World) All(yield func(entity Entity) bool) {
	for e := range  w.livingEntities.AllEntities {
		if !yield(e) {
			break
		}
	}
}

`)
//line generator/entities_go.qtpl:105
}

//line generator/entities_go.qtpl:105
func writeentitiesTemplate(qq422016 qtio422016.Writer, data *ecsTmplData) {
//line generator/entities_go.qtpl:105
	qw422016 := qt422016.AcquireWriter(qq422016)
//line generator/entities_go.qtpl:105
	streamentitiesTemplate(qw422016, data)
//line generator/entities_go.qtpl:105
	qt422016.ReleaseWriter(qw422016)
//line generator/entities_go.qtpl:105
}

//line generator/entities_go.qtpl:105
func entitiesTemplate(data *ecsTmplData) string {
//line generator/entities_go.qtpl:105
	qb422016 := qt422016.AcquireByteBuffer()
//line generator/entities_go.qtpl:105
	writeentitiesTemplate(qb422016, data)
//line generator/entities_go.qtpl:105
	qs422016 := string(qb422016.B)
//line generator/entities_go.qtpl:105
	qt422016.ReleaseByteBuffer(qb422016)
//line generator/entities_go.qtpl:105
	return qs422016
//line generator/entities_go.qtpl:105
}
