// Code generated by qtc from "events_go.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// package generator
//

//line generator/events_go.qtpl:3
package generator

//line generator/events_go.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generator/events_go.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generator/events_go.qtpl:3
func streameventsTemplate(qw422016 *qt422016.Writer, data *ecsTmplData) {
//line generator/events_go.qtpl:3
	qw422016.N().S(`
package `)
//line generator/events_go.qtpl:4
	qw422016.E().S(data.PackageName)
//line generator/events_go.qtpl:4
	qw422016.N().S(`

import "github.com/btvoidx/mint"

type EntitiesCreatedEvent struct {
	Entities []Entity
}

type EntitiesDestroyedEvent struct {
	Entities []Entity
}

type UnsubscribeFunc func()

func (w *World) OnEntitiesCreated(fn func(EntitiesCreatedEvent)) UnsubscribeFunc {
	stopCh := mint.On(w.eventBus, fn)
	return func() { stopCh() }
}

func (w *World) OnEntitiesDestroyed(fn func(EntitiesDestroyedEvent)) UnsubscribeFunc {
	stopCh := mint.On(w.eventBus, fn)
	return func() { stopCh() }
}

func fireEvent[T any](w *World, event T) {
	mint.Emit(w.eventBus,event)
}

`)
//line generator/events_go.qtpl:32
}

//line generator/events_go.qtpl:32
func writeeventsTemplate(qq422016 qtio422016.Writer, data *ecsTmplData) {
//line generator/events_go.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line generator/events_go.qtpl:32
	streameventsTemplate(qw422016, data)
//line generator/events_go.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line generator/events_go.qtpl:32
}

//line generator/events_go.qtpl:32
func eventsTemplate(data *ecsTmplData) string {
//line generator/events_go.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line generator/events_go.qtpl:32
	writeeventsTemplate(qb422016, data)
//line generator/events_go.qtpl:32
	qs422016 := string(qb422016.B)
//line generator/events_go.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line generator/events_go.qtpl:32
	return qs422016
//line generator/events_go.qtpl:32
}
