// Code generated by qtc from "relationships.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// package generator
//

//line generator/relationships.qtpl:3
package generator

//line generator/relationships.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generator/relationships.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generator/relationships.qtpl:3
func streamrelationshipTemplate(qw422016 *qt422016.Writer, data *componentTmplData) {
//line generator/relationships.qtpl:3
	qw422016.N().S(`
package `)
//line generator/relationships.qtpl:4
	qw422016.E().S(data.PackageName)
//line generator/relationships.qtpl:4
	qw422016.N().S(`
import (
    "github.com/tidwall/btree"
`)
//line generator/relationships.qtpl:8
	if data.HasAnyEvents {
//line generator/relationships.qtpl:8
		qw422016.N().S(`
    import "github.com/btvoidx/mint"
`)
//line generator/relationships.qtpl:10
	}
//line generator/relationships.qtpl:10
	qw422016.N().S(`
)

`)
//line generator/relationships.qtpl:14
	nsp := data.Name.Singular.Pascal
	nsc := data.Name.Singular.Camel
	pairName := data.Name.Singular.Pascal + "RelationshipPair"

//line generator/relationships.qtpl:17
	qw422016.N().S(`
type `)
//line generator/relationships.qtpl:19
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:19
	qw422016.N().S(` struct {
    From Entity
    To Entity
`)
//line generator/relationships.qtpl:22
	for _, f := range data.Fields {
//line generator/relationships.qtpl:22
		qw422016.N().S(`    `)
//line generator/relationships.qtpl:23
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/relationships.qtpl:23
		qw422016.N().S(` `)
//line generator/relationships.qtpl:23
		qw422016.E().S(f.Type.Singular.Original)
//line generator/relationships.qtpl:23
		qw422016.N().S(`
`)
//line generator/relationships.qtpl:24
	}
//line generator/relationships.qtpl:24
	qw422016.N().S(`}

type `)
//line generator/relationships.qtpl:27
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:27
	qw422016.N().S(`Relationship struct {
    btree *btree.BTreeG[`)
//line generator/relationships.qtpl:28
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:28
	qw422016.N().S(`]
}

func New`)
//line generator/relationships.qtpl:31
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:31
	qw422016.N().S(`Relationship() *`)
//line generator/relationships.qtpl:31
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:31
	qw422016.N().S(`Relationship {
    return &`)
//line generator/relationships.qtpl:32
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:32
	qw422016.N().S(`Relationship{
        btree: btree.NewBTreeG[`)
//line generator/relationships.qtpl:33
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:33
	qw422016.N().S(`](func(a, b `)
//line generator/relationships.qtpl:33
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:33
	qw422016.N().S(`) bool {
            ati, bti := a.To.Index(), b.To.Index()
            if ati == bti {
                return a.From.Index() < b.From.Index()
            }
            return ati < bti
        }),
    }
}

func (r *`)
//line generator/relationships.qtpl:43
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:43
	qw422016.N().S(`Relationship) Clear() {
    r.btree.Clear()
}

func(w *World) Link`)
//line generator/relationships.qtpl:47
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:47
	qw422016.N().S(`(
    to, from Entity,
`)
//line generator/relationships.qtpl:49
	for _, f := range data.Fields {
//line generator/relationships.qtpl:49
		qw422016.N().S(`    `)
//line generator/relationships.qtpl:50
		qw422016.E().S(f.Name.Singular.Camel)
//line generator/relationships.qtpl:50
		qw422016.N().S(`Arg `)
//line generator/relationships.qtpl:50
		qw422016.E().S(f.Type.Singular.Original)
//line generator/relationships.qtpl:50
		qw422016.N().S(`,
`)
//line generator/relationships.qtpl:51
	}
//line generator/relationships.qtpl:51
	qw422016.N().S(`) {
    pair := `)
//line generator/relationships.qtpl:53
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:53
	qw422016.N().S(`{
        From: from,
        To: to,
`)
//line generator/relationships.qtpl:56
	for _, f := range data.Fields {
//line generator/relationships.qtpl:56
		qw422016.N().S(`        `)
//line generator/relationships.qtpl:57
		qw422016.E().S(f.Name.Singular.Pascal)
//line generator/relationships.qtpl:57
		qw422016.N().S(`: `)
//line generator/relationships.qtpl:57
		qw422016.E().S(f.Name.Singular.Camel)
//line generator/relationships.qtpl:57
		qw422016.N().S(`Arg,
`)
//line generator/relationships.qtpl:58
	}
//line generator/relationships.qtpl:58
	qw422016.N().S(`    }

    w.`)
//line generator/relationships.qtpl:61
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:61
	qw422016.N().S(`Relationships.btree.Set(pair)
}

func(w *World) Unlink`)
//line generator/relationships.qtpl:64
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:64
	qw422016.N().S(`(from, to Entity) {
    pair := `)
//line generator/relationships.qtpl:65
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:65
	qw422016.N().S(`{
        From: from,
        To: to,
    }
    w.`)
//line generator/relationships.qtpl:69
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:69
	qw422016.N().S(`Relationships.btree.Delete(pair)
}

func (w *World) `)
//line generator/relationships.qtpl:72
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:72
	qw422016.N().S(`IsLinked(from, to Entity) bool {
    pair := `)
//line generator/relationships.qtpl:73
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:73
	qw422016.N().S(`{
        From: from,
        To: to,
    }

    _, ok := w.`)
//line generator/relationships.qtpl:78
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:78
	qw422016.N().S(`Relationships.btree.Get(pair)
    return ok
}

func (w *World) `)
//line generator/relationships.qtpl:82
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:82
	qw422016.N().S(`(to Entity) func(yield func(from Entity) bool) {
    return func(yield func(from Entity) bool) {
        iter := w.`)
//line generator/relationships.qtpl:84
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:84
	qw422016.N().S(`Relationships.btree.Iter()
        iter.Seek(`)
//line generator/relationships.qtpl:85
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:85
	qw422016.N().S(`{ To: to })
        end := `)
//line generator/relationships.qtpl:86
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:86
	qw422016.N().S(`{ To: to + 1 }

        for iter.Next() {
            item := iter.Item()
            if item.To >= end.To {
                break
            }

            if !yield(item.From) {
                break
            }
        }
    }
}

func (w *World) Remove`)
//line generator/relationships.qtpl:101
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:101
	qw422016.N().S(`Relationships(to Entity, froms ... Entity) {
    for _, from := range froms {
        pair := `)
//line generator/relationships.qtpl:103
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:103
	qw422016.N().S(`{
            To: to,
            From: from,
        }

        w.`)
//line generator/relationships.qtpl:108
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:108
	qw422016.N().S(`Relationships.btree.Delete(pair)
    }
}

func (w *World) RemoveAll`)
//line generator/relationships.qtpl:112
	qw422016.E().S(nsp)
//line generator/relationships.qtpl:112
	qw422016.N().S(`Relationships(to Entity) {
    iter := w.`)
//line generator/relationships.qtpl:113
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:113
	qw422016.N().S(`Relationships.btree.Iter()
    end := `)
//line generator/relationships.qtpl:114
	qw422016.E().S(pairName)
//line generator/relationships.qtpl:114
	qw422016.N().S(`{ To: to + 1 }

    for iter.Next() {
        item := iter.Item()
        if item.To >= end.To {
            break
        }

        w.`)
//line generator/relationships.qtpl:122
	qw422016.E().S(nsc)
//line generator/relationships.qtpl:122
	qw422016.N().S(`Relationships.btree.Delete(item)
    }
}


`)
//line generator/relationships.qtpl:127
}

//line generator/relationships.qtpl:127
func writerelationshipTemplate(qq422016 qtio422016.Writer, data *componentTmplData) {
//line generator/relationships.qtpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line generator/relationships.qtpl:127
	streamrelationshipTemplate(qw422016, data)
//line generator/relationships.qtpl:127
	qt422016.ReleaseWriter(qw422016)
//line generator/relationships.qtpl:127
}

//line generator/relationships.qtpl:127
func relationshipTemplate(data *componentTmplData) string {
//line generator/relationships.qtpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line generator/relationships.qtpl:127
	writerelationshipTemplate(qb422016, data)
//line generator/relationships.qtpl:127
	qs422016 := string(qb422016.B)
//line generator/relationships.qtpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line generator/relationships.qtpl:127
	return qs422016
//line generator/relationships.qtpl:127
}
