// Code generated by qtc from "tags.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// package generator
//

//line generator/tags.qtpl:3
package generator

//line generator/tags.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line generator/tags.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line generator/tags.qtpl:3
func streamtagTemplate(qw422016 *qt422016.Writer, data *componentTmplData) {
//line generator/tags.qtpl:3
	qw422016.N().S(`
package `)
//line generator/tags.qtpl:4
	qw422016.E().S(data.PackageName)
//line generator/tags.qtpl:4
	qw422016.N().S(`

`)
//line generator/tags.qtpl:7
	nsp := data.Name.Singular.Pascal
	nsc := data.Name.Singular.Camel
	ss := nsc + "Tags"

//line generator/tags.qtpl:10
	qw422016.N().S(`

func (w *World) TagWith`)
//line generator/tags.qtpl:12
	qw422016.E().S(nsp)
//line generator/tags.qtpl:12
	qw422016.N().S(`(entities ...Entity) (anyUpdated bool) {
    for _, e := range entities {
        if _, updated := w.`)
//line generator/tags.qtpl:14
	qw422016.E().S(ss)
//line generator/tags.qtpl:14
	qw422016.N().S(`.Upsert(e, empty{}); updated{
            anyUpdated = true
`)
//line generator/tags.qtpl:16
	if data.ShouldGenAdded {
//line generator/tags.qtpl:16
		qw422016.N().S(`            fireEvent(w, `)
//line generator/tags.qtpl:17
		qw422016.E().S(nsp)
//line generator/tags.qtpl:17
		qw422016.N().S(`AddedEvent{Entities: []Entity{e}})
`)
//line generator/tags.qtpl:18
	}
//line generator/tags.qtpl:18
	qw422016.N().S(`        }
    }

    return anyUpdated
}

func (w *World) Remove`)
//line generator/tags.qtpl:25
	qw422016.E().S(nsp)
//line generator/tags.qtpl:25
	qw422016.N().S(`Tag(entities ...Entity) (anyRemoved bool) {
    for _, e := range entities {
        if removed := w.`)
//line generator/tags.qtpl:27
	qw422016.E().S(ss)
//line generator/tags.qtpl:27
	qw422016.N().S(`.Remove(e); removed {
            anyRemoved = true
`)
//line generator/tags.qtpl:29
	if data.ShouldGenRemoved {
//line generator/tags.qtpl:29
		qw422016.N().S(`            fireEvent(w, `)
//line generator/tags.qtpl:30
		qw422016.E().S(nsp)
//line generator/tags.qtpl:30
		qw422016.N().S(`RemovedEvent{Entities: []Entity{e}})
`)
//line generator/tags.qtpl:31
	}
//line generator/tags.qtpl:31
	qw422016.N().S(`        }
    }
    return anyRemoved
}

func (w *World) Has`)
//line generator/tags.qtpl:37
	qw422016.E().S(nsp)
//line generator/tags.qtpl:37
	qw422016.N().S(`Tag(entity Entity) bool {
    return w.`)
//line generator/tags.qtpl:38
	qw422016.E().S(ss)
//line generator/tags.qtpl:38
	qw422016.N().S(`.Contains(entity)
}

func (w *World) `)
//line generator/tags.qtpl:41
	qw422016.E().S(nsp)
//line generator/tags.qtpl:41
	qw422016.N().S(`TagCount() int {
    return w.`)
//line generator/tags.qtpl:42
	qw422016.E().S(ss)
//line generator/tags.qtpl:42
	qw422016.N().S(`.Len()
}

func (w *World) `)
//line generator/tags.qtpl:45
	qw422016.E().S(nsp)
//line generator/tags.qtpl:45
	qw422016.N().S(`TagCapacity() int {
    return w.`)
//line generator/tags.qtpl:46
	qw422016.E().S(ss)
//line generator/tags.qtpl:46
	qw422016.N().S(`.Cap()
}

func (w *World) All`)
//line generator/tags.qtpl:49
	qw422016.E().S(nsp)
//line generator/tags.qtpl:49
	qw422016.N().S(`Entities(yield func(e Entity) bool) {
    for e := range w.`)
//line generator/tags.qtpl:50
	qw422016.E().S(ss)
//line generator/tags.qtpl:50
	qw422016.N().S(`.All {
        if !yield(e) {
            break
        }
    }
}

// `)
//line generator/tags.qtpl:57
	qw422016.E().S(nsp)
//line generator/tags.qtpl:57
	qw422016.N().S(`Builder
func With`)
//line generator/tags.qtpl:58
	qw422016.E().S(nsp)
//line generator/tags.qtpl:58
	qw422016.N().S(`Tag() EntityBuilderOption {
    return func(w *World, e Entity) {
        w.`)
//line generator/tags.qtpl:60
	qw422016.E().S(ss)
//line generator/tags.qtpl:60
	qw422016.N().S(`.Upsert(e, empty{})
    }
}

// Resource
func (w *World) ResourceUpsert`)
//line generator/tags.qtpl:65
	qw422016.E().S(nsp)
//line generator/tags.qtpl:65
	qw422016.N().S(`Tag() {
    w.`)
//line generator/tags.qtpl:66
	qw422016.E().S(nsc)
//line generator/tags.qtpl:66
	qw422016.N().S(`Tags.Upsert(w.resourceEntity, empty{})
}

func (w *World) ResourceRemove`)
//line generator/tags.qtpl:69
	qw422016.E().S(nsp)
//line generator/tags.qtpl:69
	qw422016.N().S(`Tag() {
    w.`)
//line generator/tags.qtpl:70
	qw422016.E().S(nsc)
//line generator/tags.qtpl:70
	qw422016.N().S(`Tags.Remove(w.resourceEntity)
}

func (w *World) ResourceHas`)
//line generator/tags.qtpl:73
	qw422016.E().S(nsp)
//line generator/tags.qtpl:73
	qw422016.N().S(`Tag() bool {
    return w.`)
//line generator/tags.qtpl:74
	qw422016.E().S(nsc)
//line generator/tags.qtpl:74
	qw422016.N().S(`Tags.Contains(w.resourceEntity)
}

// Events
`)
//line generator/tags.qtpl:78
	if data.ShouldGenAdded {
//line generator/tags.qtpl:78
		qw422016.N().S(`type `)
//line generator/tags.qtpl:79
		qw422016.E().S(nsp)
//line generator/tags.qtpl:79
		qw422016.N().S(`AddedEvent struct {
    Entities []Entity
}
func (w *World) On`)
//line generator/tags.qtpl:82
		qw422016.E().S(nsp)
//line generator/tags.qtpl:82
		qw422016.N().S(`Added(fn func(evt `)
//line generator/tags.qtpl:82
		qw422016.E().S(nsp)
//line generator/tags.qtpl:82
		qw422016.N().S(`AddedEvent)) UnsubscribeFunc {
    unsub := mint.On(w.eventBus, fn)
    return func() {
        unsub()
    }
}
`)
//line generator/tags.qtpl:88
	}
//line generator/tags.qtpl:88
	qw422016.N().S(`
`)
//line generator/tags.qtpl:90
	if data.ShouldGenRemoved {
//line generator/tags.qtpl:90
		qw422016.N().S(`type `)
//line generator/tags.qtpl:91
		qw422016.E().S(nsp)
//line generator/tags.qtpl:91
		qw422016.N().S(`RemovedEvent struct {
    Entities []Entity
}
func (w *World) On`)
//line generator/tags.qtpl:94
		qw422016.E().S(nsp)
//line generator/tags.qtpl:94
		qw422016.N().S(`Removed(fn func(evt `)
//line generator/tags.qtpl:94
		qw422016.E().S(nsp)
//line generator/tags.qtpl:94
		qw422016.N().S(`RemovedEvent)) UnsubscribeFunc {
    unsub := mint.On(w.eventBus, fn)
    return func() {
        unsub()
    }
}
`)
//line generator/tags.qtpl:100
	}
//line generator/tags.qtpl:100
	qw422016.N().S(`
`)
//line generator/tags.qtpl:102
}

//line generator/tags.qtpl:102
func writetagTemplate(qq422016 qtio422016.Writer, data *componentTmplData) {
//line generator/tags.qtpl:102
	qw422016 := qt422016.AcquireWriter(qq422016)
//line generator/tags.qtpl:102
	streamtagTemplate(qw422016, data)
//line generator/tags.qtpl:102
	qt422016.ReleaseWriter(qw422016)
//line generator/tags.qtpl:102
}

//line generator/tags.qtpl:102
func tagTemplate(data *componentTmplData) string {
//line generator/tags.qtpl:102
	qb422016 := qt422016.AcquireByteBuffer()
//line generator/tags.qtpl:102
	writetagTemplate(qb422016, data)
//line generator/tags.qtpl:102
	qs422016 := string(qb422016.B)
//line generator/tags.qtpl:102
	qt422016.ReleaseByteBuffer(qb422016)
//line generator/tags.qtpl:102
	return qs422016
//line generator/tags.qtpl:102
}
