# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.2.0

tasks:
  pb:
    dir: pb
    sources:
      - "**/*.proto"
      - "**/*.yaml"
    generates:
      - "gen/**/*"
    cmds:
      - go install github.com/bufbuild/buf/cmd/buf@latest
      - buf mod update
      - rm -rf gen
      - buf generate

  libpub:
    dir: ./library
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push origin --tags
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/geck@v{{.VERSION}}

  profile:
    dir: ./cmd/geckgen
    cmds:
      - go run main.go
      - go tool pprof -http=localhost:5432 cpu.prof

  install:
    dir: ./cmd/geckgen
    cmds:
      - go install
